FRONTEND_PATH = "static/duinoDCX_frontend/"
PORT = "/dev/ttyS0"

PING_INTEVAL = 500
TIMEOUT_TIME = 5000
SEARCH_INTERVAL = 1000

MAIN_LEFT_CHANNEL_ID: int = 5
MAIN_RIGHT_CHANNEL_ID: int = 6
SUB_CHANNEL_ID: int = 7
LOUNGE_CHANNEL_ID: int = 8
